export const allergensByType = [
  {
    type: "tree",
    allergens: [
      "acacia",
      "acer",
      "acer negundo",
      "alnus",
      "arecaceae",
      "betula",
      "carpinus",
      "carya",
      "carya illinoinensis",
      "castanea",
      "chamaecyparis obtusa",
      "corylus",
      "cryptomeria japonica",
      "cupressus",
      "eucalyptus",
      "fagus",
      "fraxinus",
      "juglans",
      "juniperus",
      "juniperus ashei",
      "ligustrum",
      "liquidambar",
      "morus",
      "olea",
      "pinus",
      "platanus",
      "populus",
      "prosopis",
      "quercus",
      "salix",
      "tilia",
      "ulmus",
    ],
  },
  {
    type: "grasses",
    allergens: [
      "agrostis",
      "anthoxanthum odoratum",
      "arrhenatherum",
      "bromus",
      "cenchrus clandestinus",
      "cynodon dactylon",
      "dactylis glomerata",
      "elymus",
      "festuca",
      "festuca pratensis",
      "holcus lanatus",
      "lolium multiflorum",
      "lolium perenne",
      "paspalum notatum",
      "phalaris",
      "phleum pratense",
      "phragmites",
      "poa pratensis",
      "sorghum halepense",
    ],
  },
  {
    type: "weeds",
    allergens: [
      "amaranthus",
      "ambrosia artemisiifolia",
      "ambrosia trifida",
      "artemisia absinthium",
      "artemisia tridentata",
      "artemisia vulgaris",
      "bellis",
      "chenopodium",
      "chenopodium album",
      "chrysanthemum",
      "helianthus",
      "humulus japonicus",
      "matricaria chamomilla",
      "mercurialis annua",
      "parietaria",
      "plantago",
      "plantago lanceolata",
      "rumex",
      "rumex acetosella",
      "salsola",
      "solidago",
      "urtica dioica",
      "xanthium strumarium",
    ],
  },
];
